export const GET_ALL_ENTRIES = "GET_ALL_ENTRIES";
export const SET_DATA_LOADING = "SET_DATA_LOADING";
export const SET_DATA_ERROR = "SET_DATA_ERROR";
export const SEARCH_ENTRIES = "SEARCH_ENTRIES";

// PLayer's
export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const REGISTER_QUEUE_SONGS = "REGISTER_QUEUE_SONGS";

// UI's
export const SWITCH_LYRICS_LANGUAGE = "SWITCH_LYRICS_LANGUAGE";
export const SWITCH_THEME = "SWITCH_THEME";
